function [thrust_prop_vec, torque_thrust_force, torque_prop_vec] = actuator_dynamics(Hopper, u)
    % in: u = [linac_pitch_p, linac_yaw_p, prop_speed_avg, prop_speed_diff]
    % out: thrust_prop_vec_b, torque_prop_vec_b

    % global r_hopper_gimbal_g

    % Constants / parameters 
    r_gimbal = Hopper.r_hopper_gimbal;

    linac_pitch = u(1);
    linac_yaw = u(2);
    prop_speed_avg = u(3);
    prop_speed_diff = u(4);

    % Thrust force and torque generated by propellers
    thrust_prop_abs = get_propeller_thrust(prop_speed_avg);
    torque_prop_abs = get_propeller_torque(prop_speed_diff);

    % intrinsic rotation: rotate the gimbal frame with -angles to get vectors in body
    % R_linac_angles = Rzyx(0, -linac_pitch, -linac_yaw)

    thrust_dir = [  cos(linac_pitch)*cos(linac_yaw)
                        -sin(linac_yaw)
                        sin(linac_pitch) * cos(linac_yaw)]; %Rzyx(0, -linac_pitch, -linac_yaw) * [1 0 0]' 

    % Force and moment generated by avg thrust
    thrust_prop_vec = thrust_prop_abs * thrust_dir;

    torque_thrust_force = Smtrx(r_gimbal)*thrust_prop_vec;

    % Moment generated by difference in propeller speeds
    torque_prop_vec = torque_prop_abs * thrust_dir; 
end


function [prop_thrust] = get_propeller_thrust(prop_speed_avg)
    prop_thrust = 1 * prop_speed_avg; % TODO
end

function [prop_torque] = get_propeller_torque(prop_speed_diff)
    prop_torque = 1 * prop_speed_diff; % TODO
end